# Generated by Django 5.1.3 on 2024-11-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='base_value',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=15),
        ),
    ]
